### ISSUE TITLE
admonitions don't get rendered correctly

### ISSUE THREAD

**Issue by warsaw** [python/peps#109]
As per http://docutils.sourceforge.net/docs/ref/rst/directives.html#note I would expect admonitions such as `.. note:` to be rendered in a text box, but that doesn't seem to be the case.  See https://www.python.org/dev/peps/pep-0339/ and https://www.python.org/dev/peps/pep-0042/ (as soon as that gets regenerated).

**Comment by berkerpeksag** [comment]
This is a duplicate of https://github.com/python/pythondotorg/issues/428.
