### ISSUE TITLE
PEP 217 has conflicting definitions or sys.displayhook interface

### ISSUE THREAD

**Issue by cben** [python/peps#1118]
https://www.python.org/dev/peps/pep-0217/#interface section said (*emphasis mine*):

> To change the way the interpreter prints interactively entered expressions, users will have to rebind `sys.displayhook` to a callable object. The *result* of calling this object with the result of the interactively entered expression *should be print-able, and this is what will be printed on `sys.stdout`*.

That's not the reality that got implemented (in either python2 or 3).  
The return value of `sys.displayhook()` is not used.  The displayhook function is responsible for skipping None, printing the value itself, as well as updating `builtins._`.

```
>>> def h(x):
    """A valid displayhook according to PEP 217 Interface section?"""
    return 'foo'
>>> import sys
>>> sys.displayhook = h
>>> 1
>>> print(_)
...
NameError: name '_' is not defined
```

However the interface implied in https://www.python.org/dev/peps/pep-0217/#solution section does match the implemented interface, contradicting Interface section.

AFAICT the reality is correctly documented (including a later unicode complication) in https://docs.python.org/2/library/sys.html#sys.displayhook and https://docs.python.org/3/library/sys.html#sys.displayhook.

I don't see any later PEPs redefining displayhook.

And as Interface and Solution sections contract each other, I guess this was simply an oversight as the PEP was edited under discussion?
So can we simply "fix" the Interface section?  Or preserve it for posterity but append a note?

**Comment by encukou** [comment]
Hi,
The documentation describes how things should actually work; PEPs archive the thoughts and discussions behind them. It is normal for a PEP to be outdated, and it's not surprising for an older PEP to be outright wrong. Also, not all changes need a PEP.
Nowadays, [it is written](https://www.python.org/dev/peps/pep-0001/#pep-maintenance) that a PEP should be edited if the *initial* implementation needs to change (and not afterwards) – but in 2000, that was an unwritten rule.

> So can we simply "fix" the Interface section? Or preserve it for posterity but append a note?

We might need to a note to *all* Final PEPs, so passers-by know that they're not reading documentation.
