### ISSUE TITLE
pep8Tabs or Spaces?

### ISSUE THREAD

**Issue by AvengerAawin** [python/peps#1273]
I know a lot of arguments have been made about this question
but I got a new point to add, so when using python IDLE after typing the if statement : if you hit enter the new line is started with tabs that means tabs is the correct choice and if you are not using tabs thinking you use spaces then you are using both.
or do all people who use tab just go to a new key by the down arrow button then hit space multiple times; if so then I think you should add that to the article

**Comment by zware** [comment]
This is not the place for such questions; this is an administrative repository for the raw PEP files.  Please take this elsewhere.
