### ISSUE TITLE
PEP 586: using asterisk (*) unpacking notation with Literal such as Literal[*some_list]

### ISSUE THREAD

**Issue by jeanmonet** [python/peps#1277]
It appears that a syntax error is currently raised if I try to define the Literal contents via *unpacking.

The use case is a list of keys for a dictionary `AllowedKeys = Literal['key1', 'key2', 'key3']` where I would want to use an existing list of those keys `keys_list = ['key1', 'key2', 'key3']` to define the `AllowedKeys = Literal[*keys_list]`.

Is there anything standing against this notation / usage, or could it be implemented in the future?

**Comment by gvanrossum** [comment]
This repo is not the place to discuss typing features. Please use the typing-sig mailing list or the https://github.com/python/typing/ repo.
