### ISSUE TITLE
PEP 427: Security issues with 3rd party dependencies included in packaging

### ISSUE THREAD

**Issue by spstarr** [python/peps#1300]
There are concerns with the Wheel binary packaging format, by allowing 3rd party shared libraries to be part of the .zip file. Security issues are not handled.

It is not advisable to bundle 3rd party libraries with a pip binary pip module, has the spec taken this into account?

If so, can someone refer me to this discussion?

**Comment by Rosuav** [comment]
At the top of the PEP, it says "Discussions-To: distutils-sig at python.org". That's the best place to ask this kind of question.
