### ISSUE TITLE
What "typing" package are you expecting?

### ISSUE THREAD

**Issue by maquino1985** [python/peps#1314]
in Python 3.7.5, typing has no TypingMeta attribute.

INTERNALERROR>     if not typing or not isinstance(type_, typing.TypingMeta) or type_ is AnyType: INTERNALERROR> AttributeError: module 'typing' has no attribute 'TypingMeta'

**Comment by Rosuav** [comment]
This repository is an administrative one for the management of PEPs themselves. I suggest asking about your issue on python-list@python.org, as it seems very likely that your problem is actually a file called typing.py in the current directory.
