### ISSUE TITLE
Rename `.txt` files to `.rst`

### ISSUE THREAD

**Issue by ks129** [python/peps#1384]
I know this is already done before but there was Git history lost. But now I have a new solution for it:
- Copy [this script](https://gist.github.com/emiller/6769886#file-git-mv-with-history) as `rename-script` to cloned (peps) repo.
- Do `chmod 700 rename-script`.
- Create a new file `renamer.py` and copy-paste this code:
```py
import os
import subprocess

for filename in os.listdir('.'):
    if filename.endswith('.txt') and filename.startswith('pep-'):
        print(f'Renaming {filename}...')
        o = subprocess.Popen(
            ['./rename-script', f'{filename}={filename.split(".")[0] + ".rst"}'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        o.communicate()
        print(f'Renamed {filename} to {filename.split(".")[0] + ".rst"}')
```
- Run this script. This will take hours, but will move git history to renamed file.
- Commit + force push

I can't do this myself because I don't want to sign this agreement (I just don't want to sign something online in this form of signing).

**Comment by Rosuav** [comment]
That would break every git commit reference, including in forked repos and everything.
