### ISSUE TITLE
PEP 617: Wrong link for Medeiros et al. paper

### ISSUE THREAD

**Issue by goodmami** [python/peps#1400]
[In PEP 617](https://www.python.org/dev/peps/pep-0617/#id11) the link for the paper by Medeiros et al. is https://arxiv.org/pdf/1509.02439v1.pdf, which is a paper on a similar topic by Laurent and Mens. The citation year for Medeiros et al. is not given, but presumably the authors intended Medeiros et al. 2014. The arXiv link is here: https://arxiv.org/pdf/1207.0443.pdf.

**Comment by gvanrossum** [comment]
Thanks! We'll fix this with #1401. Our apologies to Medeiros.
