### ISSUE TITLE
Change language from BDFL-Delegate to PEP-Delegate

### ISSUE THREAD

**Issue by warsaw** [python/peps#1431]
The Steering Council feels that the term BDFL-Delegate is an anachronism, and the time has come to change the term to PEP-Delegate.  At a minimum, this work would have to happen:

* Mass updates to existing PEP texts for those PEPs that have a `BDFL-Delegate` field
* Update the PEP 0 [generation script](https://github.com/python/peps/blob/master/pep0/pep.py#L164) to recognize `PEP-Delegate` instead.

In the meantime, we will use the terms PEP-Delegate and BDFL-Delegate interchangeably.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/peps/pull/1672.
