### ISSUE TITLE
PEP 274: uses only python 2 in examples

### ISSUE THREAD

**Issue by erl7902** [python/peps#1602]
Hi, I was looking over dictionary comprehensions and saw that it uses .iteritems and does not mention that the correct way to iterate through a dictionary in python 3 is .items() not .iteritems(). 

https://github.com/python/peps/blob/master/pep-0274.txt

**Comment by Mariatta** [comment]
A PEP is a "proposal", not a living documentation, so it can be outdated. This PEP was written for Python 2.7.
There's another PEP that proposed the removal of iteritems(): https://www.python.org/dev/peps/pep-3106/

The documentation on how to loop through dictionary in Python 3 can be read here: https://docs.python.org/3/tutorial/datastructures.html#looping-techniques
