### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sofigern** [python/peps#168]
link there is returning 404 https://github.com/python/peps/blob/master/pep-3107.txt#L278

**Comment by sofigern** [comment]
The same about https://github.com/python/peps/blob/master/pep-3107.txt#L281

**Comment by brettcannon** [comment]
Any interest in trying to find out if the relevant pages live somewhere else and submit a PR to update the links?

**Comment by brettcannon** [comment]
If there's no live site that they were moved to then archived pages are fine.
