### ISSUE TITLE
PEP 636 odd sentence

### ISSUE THREAD

**Issue by ericvsmith** [python/peps#1703]
"Your adventure is being a success and you have been asked to implement a graphical interface".

Maybe this should be "is becoming a success"? Or maybe I'm misunderstanding the sentence.

@gvanrossum @dmoisset

**Comment by gvanrossum** [comment]
Hm, you're right. Can either you or @dmoisset send in a PR to fix it?

**Comment by ericvsmith** [comment]
PR #1705
