### ISSUE TITLE
PEP-333

### ISSUE THREAD

**Issue by valq7711** [python/peps#1725]
Hello!
The `SCRIPT_NAME` header is there, and that's okay!
But what about the opposite situation, where the application is served under a domain that is mapped to a prefix path? In common case  there can be multiple domains mapped to the corresponding prefix paths of the same application.
Suppose request comes with full path in `PATH_INFO` (provided by proxy server that does mapping), but to reconstruct the original url we need to know the mapped prefix, i.e. hidden part of the full path.  
So is it possible to introduce some standard header like `MAPPED_URL` or `HIDDEN_PREFIX` or `REVERSE_SCRIPT_NAME` containing the prefix of  the full path that is not in original url? I.e. 
```python
original_path = PATH_INFO[len(HIDDEN_PREFIX):]
```
thanks in advance

**Comment by Rosuav** [comment]
This isn't the place to ask about this. Try python-list@python.org.
