### ISSUE TITLE
PEP 440: Impossible example

### ISSUE THREAD

**Issue by wyz23x2** [python/peps#1731]
[PEP 440/version specifiers](https://www.python.org/dev/peps/pep-0440/#version-specifiers):
> A version specifier consists of a series of version clauses, separated by commas. For example:  
> ``~= 0.9, >= 1.0, != 1.3.4.*, < 2.0``  

This is impossible, as ``~=0.9`` means ``>=0.9, ==0.*``.

**Comment by brettcannon** [comment]
Your best option for seeing this fixed is to bring this up at https://discuss.python.org/c/packaging/14.
