### ISSUE TITLE
PEP 224 does not seem to consider how to document dynamic properties - non-static member variables of instance

### ISSUE THREAD

**Issue by poikilos** [python/peps#1737]
Most of the time, we are dealing with non-static variables. How will we document them?
- Do we have to do `ClassName.__doc_someVariable__` manually since dynamic properties aren't covered by PEP 224?
  - but...shouldn't non-static ones be documented differently than static ones somehow?

Possible solutions (obviously they have some shortcomings):

### inline quotes
Odd but ok:
```
class ClassName:
    StaticMember = "abc"
    def __init__(self):
        self.someVariable = "def"
        "This may work, but who knows what's here. Hopefully the developer will notice the problem after generating documentation"
```

### block comments
This may in edge cases, but the stuff in quotes is usually means comments related to init, I would presume, not variables. Existing code that puts this long quote before instead of after variable being documented (or has comments not variable-specific) would need to change.
```python
class ClassName:
    StaticMember = "abc"
    def __init__(self):
        self.someVariable = "def"
        """"
        This might be something else, but may be ok.
        This is a very long comment, and sometimes this may be about a variable, but other times logic.
        """"
```

**Comment by Rosuav** [comment]
PEP 224 is rejected. I'd suggest discussing this matter on python-list or similar rather than here.
