### ISSUE TITLE
PEP 343: vague possibility of tracing with-statements [e.g. with lock objects]

### ISSUE THREAD

**Issue by mhmdkanj** [python/peps#1742]
Any new scope entered or exited could be traced by defining a custom tracing function and setting it using the [sys](https://docs.python.org/3/library/sys.html) module through [sys.settrace()](https://docs.python.org/3/library/sys.html#sys.settrace) or [sys.setprofile()](https://docs.python.org/3/library/sys.html#sys.setprofile). This is also true for multithreaded applications using the [threading](https://docs.python.org/3/library/threading.html) module.

Thus, it is rather vague whether the `__enter__()` and `__exit__()` functions executed by a `with` statement could be traced, and if so, in what cases. For instance, `_thread.LockType` or simply primitive lock objects from `threading` being used with the context management, or the `with` statement, might not allow us to trace a lock being acquired or released, or in other words whether the `__enter__()` function that calls `acquire()` is called. After some experimentation, unfortunately this is not the case if either Python or C functions (for CPython) are traced.

Cc: @gvanrossum

**Comment by gvanrossum** [comment]
This repo is not for discussion of PEP content. If you have a question about this PEP I recommend writing to python-ideas.
