### ISSUE TITLE
How does "Knuth's style" for line breaks translate to code?

### ISSUE THREAD

**Issue by gsganden** [python/peps#186]
PEP 8 says the following:

> In Python code, it is permissible to break before or after a binary operator, as long as the convention is consistent locally. For new code Knuth's style is suggested.

However, I don't see how Knuth's style applies to code. Knuth's style distinguishes between formulas within paragraphs and displayed formulas. What is the analogous distinction in a coding context?

**Comment by gvanrossum** [comment]
In this context, "Knuth's style" refers to the immediately preceding example, i.e. break *before* binary operators. We should consider Python code always to be equivalent to "displayed formulas".
