### ISSUE TITLE
PEP 621: does the file have to be called `pyproject.toml`?

### ISSUE THREAD

**Issue by pxeger** [python/peps#1897]
PEP 621 doesn't formally specify that the filename of the `pyproject.toml` has to be so. It reads as though it's supposed to be, but itsn't explicitly mentioned in the Specification. I think it should be formally clarified.

**Comment by pradyunsg** [comment]
PEP 621's title is:

> Storing project metadata in pyproject.toml

Further, the abstract is literally just:

> This PEP specifies how to write a project's core metadata [1] in a pyproject.toml file for packaging-related tools to consume.

I think it's pretty clear that the file has to be called pyproject.toml, and no further clarification is needed.
