### ISSUE TITLE
PEP 480: update distribution upload steps

### ISSUE THREAD

**Issue by brainwane** [python/peps#1912]
@mnm678 The section about PyPI users registering projects prior to uploading https://github.com/python/peps/blob/e2b198bf251d14c6e77d83ad391590a9e3665122/pep-0480.txt#L380-L395

 is now obsolete and needs to be updated before or as we re-start deliberations on this PEP.

_Originally posted by @brainwane in https://github.com/python/peps/issues/1693#issuecomment-717544900_

**Comment by brettcannon** [comment]
We try to keep this issue repository just for the repo itself and not the individual PEPs (too many of them for us to be a central clearinghouse for that sort of thing). I would email the PEP authors to find out where they want feedback to go.
