### ISSUE TITLE
Let's rename the master branch to main

### ISSUE THREAD

**Issue by gvanrossum** [python/peps#1956]
Does this require any notifications? Or should we just do it?

**Comment by Mariatta** [comment]
Related https://github.com/python/devguide/issues/689

In the [Steering Council announcement](https://mail.python.org/archives/list/python-dev@python.org/thread/XCUXKL5LMQHO7GDQUABS4KE6JSMRVUQN/#GDAUZKYB6GP3A3ZGBSQ4KQ7R6QFIZHZC), it says:

> The group is going to discuss the
>   timeline and how to approach this with **other repositories under the Python**
>   organization in some future meeting.

I was wondering if there's been any further update/discussion on that.

**Comment by brettcannon** [comment]
We plan on doing it, we just need to figure out the when and who is going to handle it for all the repos (probably want to do it at once instead of incrementally/ad-hoc).

I put it on the agenda for the next steering council meeting.

**Comment by gaborbernat** [comment]
Any updates on this @brettcannon? 😊

**Comment by brettcannon** [comment]
I believe the current plan is the PSF infrastructure team is going to handle the other repos like this one. I don't have an ETA, though. But it will be happening at some point.

**Comment by hugovk** [comment]
This can be closed now, `main` is now the default branch, see also https://github.com/python/peps/pull/2176.

**Comment by ewdurbin** [comment]
This is complete.
