### ISSUE TITLE
GH pages lacks styling

### ISSUE THREAD

**Issue by brettcannon** [python/peps#2005]
https://python.github.io/peps/

**Comment by Rosuav** [comment]
Looks like the same as #2006 - the CSS is being referenced from ../_static which is not available here.

**Comment by Rosuav** [comment]
(Or more precisely, they're assuming a particular path structure, which is breaking both styling and links)

**Comment by AA-Turner** [comment]
Sorry I missed this - this is expected and should be fixed with #1933. https://aa-turner.github.io/peps/ has the theming branch applied, and both issues are resolved.

A

**Comment by pablogsal** [comment]
Fixed by https://github.com/python/peps/pull/1933
