### ISSUE TITLE
PEP 541 email address support@npmjs.com might be incorrect

### ISSUE THREAD

**Issue by gemerden** [python/peps#2026]
PEP 541 proposes that in case I would like to request a package name from PyPi to be removed, I contact the maintainer with a CC to support@npmjs.com. However this gives me an auto-reply with "create a ticket ...". 

My question is: does npmjs.com handle PyPi package names and if not, where do i go? If so, is creating a ticket the right way to go?

It might be a good idea to update the instructions for these kind of cases.

In this case I want to create a package under a name the maintainer is using, but the current package cannot be installed. there are no docs, no homepage, etc. (the package name is 'snapshot')

**Comment by Rosuav** [comment]
NPM has no connection to PyPI. What you're reading there is a summary of *prior art* - that is to say, other people doing similar things to what is proposed. Look at the previous section, which explains how Python is doing things.
