### ISSUE TITLE
PEP 563: Update references to full adoption from 3.10 to 3.11

### ISSUE THREAD

**Issue by xochozomatli** [python/peps#2084]
The PEP 563 page still states that it will be adopted as default behavior in 3.10 rather than 3.11. There are two such references: one under "Implementation" and one under "Deprecation policy" in "Backwards Compatibility".

**Comment by gvanrossum** [comment]
It is not clear that it will be adopted at all. See PEP 649. We should probably weaken the wording in PEP 563. Could you submit a PR?
