### ISSUE TITLE
"PEP numbers never change" verbiage is not in PEP 1

### ISSUE THREAD

**Issue by AndreasChristianson** [python/peps#2087]
## Problem

The introduction to PEP 0 references PEP 1 as a source for

> PEP numbers are assigned by the PEP editors, and once assigned are never changed [1].

But PEP 1 doesn't say anything about PEP numbers never changing.

## Research

While skimming PEP 1, I found information about the PEP editor assigning a number:

> Once the PEP is ready for the repository, a PEP editor will:
Assign a PEP number (almost always just the next available number, but sometimes it's a special/joke number, like 666 or 3141). (Clarification: For Python 3, numbers in the 3000s were used for Py3k-specific proposals. But now that all new features go into Python 3 only, the process is back to using numbers in the 100s again. Remember that numbers below 100 are meta-PEPs.)

and

> The PEP editors are individuals responsible for managing the administrative and editorial aspects of the PEP workflow (e.g. assigning PEP numbers and changing their status). See PEP Editor Responsibilities & Workflow for details.

But I didn't find any reference to that number never changing. 

## Proposal:

Can we change PEP 0's introduction so that the reference is specific to assigning numbers?

```
PEP numbers are assigned by the PEP editors[1], and once assigned are never changed.
```

## Link

https://github.com/python/peps/blob/40ef5625b7d42655f49090ffd2c0860ecf8d1d9f/pep0/constants.py#L22-L27

**Comment by gvanrossum** [comment]
Sounds good. Can you submit a PR?

**Comment by AndreasChristianson** [comment]
> Sounds good. Can you submit a PR?

Done
