### ISSUE TITLE
Update PEP 13 now that election has concluded and the new Council has taken office

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/peps#2268]
@python/psf-election-adminstrators , PEP 13 needs updating by someone authoritative, namely one of you I presume, now that the Steering Council election has been finalized and the new Steering Council has taken office, as it still lists the old Council. Thanks!

**Comment by hugovk** [comment]
I created PR https://github.com/python/peps/pull/2272, the last update (https://github.com/python/peps/pull/1946) was merged by an SC member/PEP editor.
