### ISSUE TITLE
Library 

### ISSUE THREAD

**Issue by Abbasghfrt** [python/peps#2469]
Hello, I think if you can find 30 libraries Implement the languages ​​of other languages ​​in Python. Python is the best, for example 👍 :
Import stdio for c++
Import windows. Form for c#
Import java.util.scanner for javo
And java script ,r 
But if you can add a module that converts code directly into machine language 0.1, both the speed and the usage will increase.

**Comment by Rosuav** [comment]
This isn't the place to suggest that. Try the python-list mailing list.
