### ISSUE TITLE
PEP forwarding links sometimes broken?

### ISSUE THREAD

**Issue by gvanrossum** [python/peps#2505]
See https://mail.python.org/archives/list/python-dev@python.org/message/YCIGD63IKLRE7JFMDLSUU4KN3DOUNURD/

It looks like the old like for e.g. PEP 646 doesn't work.

**Comment by zware** [comment]
For some reason, it looks like the unrendered Markdown links occasionally include the trailing `)` in the automatically created link (wherever those links are being automatically created).  I'm not sure there's anything to do for that other than to avoid unrendered Markdown in email.

**Comment by gvanrossum** [comment]
Okay, so it was an issue in Pablo's email, not with PEP rendering. Closing. Sorry!
