### ISSUE TITLE
Why is the matching pattern opposite to that of bash?

### ISSUE THREAD

**Issue by dcvcv** [python/peps#2570]
All matches do not perform any operations, only one - option will perform operations, and enter with so many conditions to find a mismatch to perform, the processing is too limited, and if it is the same as bash's case, it is not bad. Matching execution, unmatching add your own processing method, which is not better

**Comment by Rosuav** [comment]
This isn't the place to ask this sort of thing. I would suggest trying the mailing list python-list@python.org instead.
