### ISSUE TITLE
Certified Translation Service in Singapore | Certified Translator

### ISSUE THREAD

**Issue by n069** [python/peps#2595]
https://www.eliteasia.co/business-localisation/certified-translation-services/?gclid=CjwKCAjw9-KTBhBcEiwAr19igy6c1JJ5LhCTxBM3lxhVzmTdvMS8iNG4rai1P_r3MMS4KbwKZrUmYxoCuWkQAvD_BwE

**Comment by Mariatta** [comment]
Not applicable here.

**Comment by n069** [comment]
https://github.com/python/peps/issues/2595
