### ISSUE TITLE
Get paid for answering short surveys. Download Google Opinion Rewards now: https://googleopinionrewards.page.link/share

### ISSUE THREAD

**Issue by n069** [python/peps#2597]
https://www.lifepointspanel.com/en-my/login

**Comment by Mariatta** [comment]
Spam

**Comment by CAM-Gerlach** [comment]
@JelleZijlstra @gvanrossum @warsaw @brettcannon You're repo admins; can you actually delete these spam issues (after reporting them)?

**Comment by ezio-melotti** [comment]
I blocked the user.
