### ISSUE TITLE
PEP-0492: Change `else` in semantically equivalent block to `finally`

### ISSUE THREAD

**Issue by slateny** [python/peps#2602]
In the [language reference](https://docs.python.org/3/reference/compound_stmts.html#async-with) the `else` was replaced with `finally` in [this pr](https://github.com/python/cpython/pull/17608), and a bunch of variables were renamed too. Should this change be ported over to the [PEP](https://peps.python.org/pep-0492/#asynchronous-context-managers-and-async-with)?

**Comment by AA-Turner** [comment]
No, the PR is Final. The language reference now serves as the authoritative documentation.

A
