### ISSUE TITLE
PEP 545 references the inactive The Knights Who Say Ni project

### ISSUE THREAD

**Issue by Mariatta** [python/peps#2612]
In **PEP 545 Python Documentation Translations**, it says 

> To help ensuring contributors from GitHub have signed the Documentation Contribution Agreement, We can setup the “The Knights Who Say Ni” GitHub bot customized for this agreement on the migrated repositories

The Knights Who Say Ni has been deactivated and we're using the CLA bot now.

Perhaps the text should be updated. 

Url: https://peps.python.org/pep-0545/#setup-a-github-bot-for-documentation-contribution-agreement

Source: https://github.com/python/peps/blob/83148efae2643e62063efc2ea0822b1b39f1d792/pep-0545.txt#L418-L420

**Comment by AA-Turner** [comment]
PEP 545 is Final, hence we'd tend not to update it. It seems the current authoritative source for operational translation is https://devguide.python.org/documenting/#translating.

A
