### ISSUE TITLE
Mark rejected alternative proposals with a red color in PEP

### ISSUE THREAD

**Issue by vainaixr** [python/peps#2615]
https://discuss.python.org/t/mark-rejected-alternative-proposals-with-a-red-color-in-pep/15720

**Comment by AA-Turner** [comment]
I don't think this is a good idea, especially now there's a sidebar with the table of contents it should be fairly easy to see that the heading you're reading is in 'Rejected Ideas'.

If another editor disagrees with me, feel free to re-open for more discussion.

A

**Comment by CAM-Gerlach** [comment]
Making code samples in the Rejected Ideas section have a certain background color seems rather esoteric, hacky, bespoke and not always applicable, when it should be left up to the author to decide.

It might be useful more broadly, though, to have a way to explicitly mark a code block as a known bad (broken, insecure, unreliable, etc) example, e.g. making its background color red or warning striped, as a deterrent to people copying it without paying close attention. The easiest way I'd reckon is to just have a CSS rule that does this, applied via `:class:` or `rst-class::` on the code blocks in question. But I'm not sure how widely used it would be, unless we specifically promote it to PEP authors.

(Also, changing the close reason for now to a more appropriate one, until if/when we decide to re-open).
