### ISSUE TITLE
including pyd files

### ISSUE THREAD

**Issue by AbdelsalamHaa** [python/peps#2788]
I'm trying to build a package which contains pyd files.  I have tried to build the package but all the time the pyd files are not included. 
Here is my pyproject.toml 

```
requires = ["flit_core>=3.2"]
build-backend = "flit_core.buildapi"


[project]
name = "iRadar_AIV"
version = "0.0.1"
authors = [
  { name="Name", email="abd.a@mail.com" },
]
description = "AIV Backend Project"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
```

**Comment by JelleZijlstra** [comment]
This repo is for managing the Python Enhancement Proposal (PEP) process, not for specific technical questions. I would suggest asking your question at https://discuss.python.org/c/packaging/14.
