### ISSUE TITLE
Link to PEP 547 is broken.

### ISSUE THREAD

**Issue by Dude-X** [python/peps#281]
The link to https://www.python.org/dev/peps/pep-0547/ leads to a 404 page.

**Comment by ned-deily** [comment]
The link is broken because the text of pep-0547.rst has several errors and does not build.  @Traceur759 and @ncoghlan

**Comment by ncoghlan** [comment]
Thanks for the heads up (I'd assumed the missing page was just the usual cache invalidation problem, and didn't go back to check for actual rendering problems)

https://github.com/python/peps/commit/5f17b7a5d9f84923288767a802fc45387059d070 fixed the errors for me locally, so it should show up on the site soon.
