### ISSUE TITLE
Walrus operator without parenthesis in Jupyter notebooks

### ISSUE THREAD

**Issue by avloss** [python/peps#2831]
Would be great to have walrus operator working without parenthesis, so that Jupyter Notebook would show assigned value. I understand it wasn't designed for that, but within a notebook it can be really handy to see assigned value after the cell is executed. Right now, the solution is to use write variable again or to use parenthesis.

* Current solution Option 1:
```ipyhon
dataframe = complex_function(complex_arguments)
dataframe
```
* Current solution Option 2:
```ipyhon
(dataframe := complex_function(complex_arguments))
```
* Desired behaviour:
```ipython
dataframe := complex_function(complex_arguments)
```

(I know there's probably a discussion somewhere, or this is not the right place to put this issue. I'm apologising in advance for spamming the board.)

**Comment by Rosuav** [comment]
Thanks, good to know.

**Comment by avloss** [comment]
Thanks, will have a look at Ideas category on Discourse!
