### ISSUE TITLE
A concrete proposal for implementing this, roughly based on the concensus in the aforementioned thread, is:

### ISSUE THREAD

**Issue by Red3amer** [python/peps#2836]
A concrete proposal for implementing this, roughly based on the concensus in the aforementioned thread, is:

- Add an optional `Track` header for PEPs, that can have only one value for the initial implementation: `Packaging`.
  - Add this header to existing Python Packaging PEPs.
- Add a track-specific index page, that lists all PEPs with that track: `peps.python.org/track/packaging`
  - This page should have a different header and introduction section than PEP 0.

The Track header can be expanded to other values in the future (`Typing` and `Release` are examples of proposed ideas from the aforementioned thread).

Personally, I think it's valuable to implement this for just Packaging as an initial pass since it's a viable "minimum" implementation of this mechanism and... perhaps more importantly... avoids an extended discussion on what these other values should be allowed/updated for. :)

_Originally posted by @pradyunsg in https://github.com/python/peps/issues/2572#issuecomment-1116528580_

**Comment by CAM-Gerlach** [comment]
@python/organization-owners :point_up: spammer, please deal with it:

* This is just a `Reference in new issue` autocreated issue from a closed/completed issue/PR, with no plausible bona-fide reason for creating it
* Nearly brand new account, only 1.5 mo old
* Account's only meaningful contributions are two spam reviews on random repos consisting entirely of the text `...`
* Only other account activity are a a few empty/auto-created placeholder repos and commits to the same, and a handful of forks
