### ISSUE TITLE
PEP 0383: Broken attribution link

### ISSUE THREAD

**Issue by textshell** [python/peps#2862]
The link to "Markus Kuhn’s idea that he called UTF-8b" got broken again when gmane shut down.
From looking at the history i think a working replacement link is
https://web.archive.org/web/20090830064219/http://mail.nl.linux.org/linux-utf8/2000-07/msg00040.html

(submitting as issue because CLA requirements for pull requests)

**Comment by hugovk** [comment]
Thanks, please see PR https://github.com/python/peps/pull/2863.
