### ISSUE TITLE
PEP 698: What is the order of `@override` with respect to other decorators like `@property` and `@overload`?

### ISSUE THREAD

**Issue by bzoracler** [python/peps#2904]
Under https://peps.python.org/pep-0698/#specification, it is mentioned that

> The `@override` decorator should be permitted anywhere a type checker considers a method to be a valid override, which typically includes not only normal methods but also `@property`, `@staticmethod`, and `@classmethod`.

However, none of the examples provide mention of combining `@override` with these. From the signature at [`typing_extensions.pyi`](https://github.com/python/typeshed/blob/main/stdlib/typing_extensions.pyi)

```python
_F = typing.TypeVar("_F", bound=Callable[..., Any])

...

def override(__arg: _F) -> _F: ...
```

it looks immediately incompatible if it goes above `@property` or `@classmethod`, which don't have `__call__`, unless type-checkers special case `@override` to handle those. Together with https://peps.python.org/pep-0698/#limitations-of-setting-override

> - The `@override` decorator needs to execute after ordinary decorators like `@functools.lru_cache` that use wrapper functions, since we want to set `__override__` on the outermost wrapper. This means it needs to go above all these other decorators.
> - But `@override` needs to execute before many special descriptor-based decorators like `@property`, `@staticmethod`, and `@classmethod`.

Is it correct to assume that `@override` goes **below** `@property`, `@staticmethod`, `@classmethod`, `@overload`?

**Comment by brettcannon** [comment]
> > * But `@override` needs to execute before many special descriptor-based decorators like `@property`, `@staticmethod`, and `@classmethod`.
> 
> Is it correct to assume that `@override` goes **below** `@property`, `@staticmethod`, `@classmethod`, `@overload`?

Yep!
