### ISSUE TITLE
Make peps.python.org exist

### ISSUE THREAD

**Issue by brettcannon** [python/peps#3]
Could be hosted on Read the Docs.

Depends on #2 .

**Comment by brettcannon** [comment]
This would make www.python.org/dev/peps/* become redirects to peps.python.org as appropriate.

**Comment by pradyunsg** [comment]
@brettcannon Has this idea been abandoned?

**Comment by pradyunsg** [comment]
> @brettcannon Has this idea been abandoned?

A gentle ping.

**Comment by brettcannon** [comment]
@pradyunsg I'm not pushing it anymore (which is why I closed it). If someone else wants to try and make it work they can, but it's a surprisingly large task.
