### ISSUE TITLE
Numbers in scientific notation are assumed to be floats

### ISSUE THREAD

**Issue by pmlpm1986** [python/peps#3144]
I have recently updated to Python 3.11 from 3.8 and started getting warnings about randrange() only accepting integers as inputs. I thought I was only using integers with the randrange() but I realised that by using scientific notation I always get floats even though I specify integer numbers (e.g., 1e6). Scientific notation is mainly meant for convenience and therefore having to write "int(1e6)" is not helpful. One might as well write 1000000. 

Obviously, this is not a huge problem, simply  annoying, and so I was wondering: what was the reasoning behind the decision to assume all numbers in scientific notation are floats? Is there PEP for this? Could this be changed in the future?

**Comment by JelleZijlstra** [comment]
The PEPs repo is meant only for discussing specific problems with PEPs, not for general discussion about the language. I would recommend you ask your question at https://discuss.python.org/c/users/7.
