### ISSUE TITLE
PEP 715: typo (repeating "of")

### ISSUE THREAD

**Issue by UriyaHarpeness** [python/peps#3201]
While reading the PEP, this small typo popped for me.
https://github.com/python/peps/blob/76b6939fe53bb3a519d06afc620ad0e9bee2518e/pep-0715.rst?plain=1#L74

**Comment by UriyaHarpeness** [comment]
Seems like you're the author @woodruffw.

**Comment by hugovk** [comment]
@UriyaHarpeness Good spot, would you like to create a PR to fix it?

**Comment by UriyaHarpeness** [comment]
Actually I would if that's ok, just need a few hours as I just saw it on my phone.

**Comment by UriyaHarpeness** [comment]
https://github.com/python/peps/pull/3202
@hugovk @woodruffw

**Comment by UriyaHarpeness** [comment]
Also, my PyCharm also warns about duplications in `pep_sphinx_extensions/pep_theme/static/style.css`, should I open another PR to fix them?
And I also see some occurrences in specific PEPs where `’` is used in words like didn’t or it’s, can I also open another PR to change all of these to the more commonly used `'`?

**Comment by woodruffw** [comment]
Please feel free to send a PR for the typo in my PEP; otherwise, I'll get around to it later today or this weekend.

The PEP maintainers probably have separate opinions about cleaning up the CSS and quotation choices 🙂

**Comment by hugovk** [comment]
Fixed in https://github.com/python/peps/pull/3202, thanks!

CSS - yes please.

Apostrophes - let's leave them be.
