### ISSUE TITLE
How to glorify PEP 668

### ISSUE THREAD

**Issue by MaKaNu** [python/peps#3265]
I must admit I had a complete different starting point into the topic of venv as others. I used them pretty much from the beginning, where I was still coding only on windows. Over the past few years I explained to my students and colleagues why it is important to learn venv. I mostly pointed them to the documentation venv. I am happy that those days seems to be gone.

So that PEP 668 is now helping me spreading the message and reducing time effort I wanted to buy a t-shirt. Sadly the querry "pep 668 tshirt" returns mostly underpants.

So my question what should a T-shirt show which glorify PEP 668?

**Comment by hugovk** [comment]
This issue tracker isn't the place to discuss this sort of thing, try https://discuss.python.org instead.
