### ISSUE TITLE
PEP 673

### ISSUE THREAD

**Issue by sivajik34** [python/peps#3287]
def set_scale(self,scale:float) -> Shape:

NameError: name 'Shape' is not defined

We need to use a string literal 'Shape'  and not Just Shape

**Comment by JelleZijlstra** [comment]
I don't think this is spam; it's pointing out that one of the code samples in PEP-673 would throw a NameError if run. However, it works correctly with `from __future__ import annotations` (PEP-585) applied, and there's no need to change the PEP.

**Comment by AA-Turner** [comment]
> I don't think this is spam; it's pointing out that one of the code samples

Good point, somehow I saw 673 and read 723(!), to which the body was a non-sequitur -- apologies for the noise here. I've restored the content with formatting & re-titled.

A
