### ISSUE TITLE
Question: when is PEP 517 going to be completed?

### ISSUE THREAD

**Issue by xoviat** [python/peps#342]
I have attempted multiple times to discover this information but no one seems to know.

**Comment by brettcannon** [comment]
You will have to ask the authors or on distutils-sig (this issue tracker is for how we manage PEPs, not individual PEPs).

**Comment by xoviat** [comment]
I have already attempted to ask on distutils-sig and no one there seemed to know either. The discussion regarding that PEP seems to have stopped, but the PEP remains in draft status.

**Comment by brettcannon** [comment]
Yep, so it will stay a draft until the authors say it's finished.
