### ISSUE TITLE
PEP 282: Broken log4j link

### ISSUE THREAD

**Issue by betayu528** [python/peps#3465]
When I read the [pep282] (https://peps.python.org/pep-0282/),   I found the link of References about log4j is 404 

details: 
log4j: a Java logging package, link   "http://jakarta.apache.org/log4j/docs/index.html" is unavailable

**Comment by hugovk** [comment]
Thanks, would you like to open a PR to fix it? https://logging.apache.org/log4j/ looks like a good option.
