### ISSUE TITLE
Posted to distutils-sig here: https://mail.python.org/pipermail/distutils-sig/2018-January/031920.html

### ISSUE THREAD

**Issue by totalavatar** [python/peps#3507]
Posted to distutils-sig here: https://mail.python.org/pipermail/distutils-sig/2018-January/031920.html

(I don't expect anyone to object to that plan, but I'll give folks some time to comment before making the change)

_Originally posted by @ncoghlan in https://github.com/python/peps/issues/560#issuecomment-361040187_
            
```[tasklist]
### Tasks
```

**Comment by encukou** [comment]
This has been fixed in #1123 in 2019. Please check the current version of PEP-508.
