### ISSUE TITLE
Docstring question

### ISSUE THREAD

**Issue by kesha1226** [python/peps#3661]
https://github.com/python/peps/blob/53c3d1a703e4f3208c59699f9ad7e313919327cf/peps/pep-0008.rst?plain=1#L868 

Does this mean that each of my functions must have a docstring, even if it is a single line or the only one in the file? Or if this function is the only one written exclusively for the programming competitions?

**Comment by hugovk** [comment]
This issue tracker is for the authoring of PEPs, please could you open your question at the discussion forum?

https://discuss.python.org/c/users/7
