### ISSUE TITLE
Redundant else statement in function `foo`

### ISSUE THREAD

**Issue by 1chooo** [python/peps#3738]
https://github.com/python/peps/blob/e9a60482a11bd058136e6229a80eb82e9b20c9c3/peps/pep-0008.rst?plain=1#L1416

In the function `foo` defined in the code, the `else` statement seems to be redundant. The condition `x >= 0` in the if statement already covers **the scenario where x is not less than 0**. If x is less than 0, the control will directly move to the next line after the if block. Therefore, we can directly return None without the need for the `else` statement, similar to what is done in the function bar. This will make the code cleaner and more readable.

```py
# Correct:

def foo(x):
    if x >= 0:
        return math.sqrt(x)
    else:       # No need to check x < 0, as the previous condition already covers it
        return None

def bar(x):
    if x < 0:
        return None
    return math.sqrt(x)
```

### Corrected

```py
# Correct:

def foo(x):
    if x >= 0:
        return math.sqrt(x)
    return None

def bar(x):
    if x < 0:
        return None
    return math.sqrt(x)
```

**Comment by gvanrossum** [comment]
Sorry, but that example is as we intended.
