### ISSUE TITLE
status of Python 3.13b2?

### ISSUE THREAD

**Issue by greenozon** [python/peps#3826]
it is marked to be released 3 days ago over here...
https://peps.python.org/pep-0719/

**Comment by hugovk** [comment]
It was released yesterday:

* https://discuss.python.org/t/3-13-0b2-now-available/55056
* https://www.python.org/downloads/release/python-3130b2/

3.12.4 will be release soon as well, there's a last minute bug that needs fixing. We'll probably update the PEPs for both when 3.12 is out.
