### ISSUE TITLE
PEP 665: link to "replaced by"

### ISSUE THREAD

**Issue by davidszotten** [python/peps#3874]
Some peps replace other previous peps. it would be nice if the page for replaced peps also linked to their replacements

**Comment by hugovk** [comment]
Please can you give an example?

**Comment by davidszotten** [comment]
https://peps.python.org/pep-0751/

<img width="351" alt="image" src="https://github.com/user-attachments/assets/fc731bc0-8e41-43fe-bfee-24082ff4863c">

**Comment by davidszotten** [comment]
(this was prompted by me trying to find the new one and accidentally initially landing on the old one)

**Comment by hugovk** [comment]
We have a [Superseded-By header](https://peps.python.org/pep-0001/#pep-header-preamble) for this.

For example, compare https://peps.python.org/pep-3153/ -> https://peps.python.org/pep-3156/

Let's also add Superseded-by: 751 to PEP 665: please see PR https://github.com/python/peps/pull/3875.

**Comment by davidszotten** [comment]
🎉 thanks!

**Comment by davidszotten** [comment]
looks like there are a bunch more inconsistencies between the replaces and superseded-by

should they all be in sync? do we care enough to fix? to add some tool to detect future ones?

e.g.

```
-    "3124": "245, 246",
-    "402": "382",
+    "387": "5",
-    "426": "345",
-    "443": "245, 246, 3124",
-    "449": "381",
-    "452": "247",
-    "464": "381",
-    "487": "422",
-    "600": "513, 571, 599",
+    "600": "599",
+    "621": "631",
-    "723": "722",
-    "742": "724",
```

**Comment by hugovk** [comment]
@AA-Turner What do you think? ^
