### ISSUE TITLE
PEP 526: broken link

### ISSUE THREAD

**Issue by shurshilov** [python/peps#4024]
404 link in [Implementation](https://peps.python.org/pep-0526/#implementation)

https://github.com/ilevkivskyi/cpython/tree/pep-526

**Comment by AA-Turner** [comment]
cc @ilevkivskyi

**Comment by JelleZijlstra** [comment]
Probably best to retarget that link to the PR that actually added support.

**Comment by ilevkivskyi** [comment]
OK, I think what happened is that at the time of PEP CPython was still on `hg`, and the `git` version only existed as a mirror. I pushed the branch to my fork of the mirror, but when CPython moved to `git` officially I replaced my fork with a fork of the official repo, thus deleting all previous branches.

So there is no PR, but I can try to find the final `hg` patch that was applied.

**Comment by ilevkivskyi** [comment]
OK, I think this is the patch that was applied https://hg.python.org/cpython/rev/49533a9fe322

**Comment by hugovk** [comment]
Which is https://github.com/python/cpython/commit/f8cb8a16a344ab208fd46876c4b63604987347b8 in Git.

**Comment by ilevkivskyi** [comment]
https://github.com/python/peps/pull/4031 should fix this.
