### ISSUE TITLE
Allow adding a date to the Resolution of a PEP

### ISSUE THREAD

**Issue by JelleZijlstra** [python/peps#4054]
Currently, the Resolution field just has a link. It was brought up in the PEP 735 discussion (https://discuss.python.org/t/pep-735-dependency-groups-in-pyproject-toml/39233/323) that it can be useful to also have the acceptance date, since it may be long after any date in the Post-History. The acceptance date is especially relevant for PEPs such as those in the packaging space, which aren't tied to the CPython release cycle. However, for all PEPs it seems useful to be able to see at a glance when it was accepted.

I'd propose to add the acceptance date to the headers (maybe a new Resolution-Date header?) for future PEPs. If someone is interested in doing the work, we can also backfill this for past PEPs.

cc @gaborbernat @pfmoore @sirosen from the Discourse discussion.

**Comment by hugovk** [comment]
Sounds good.

Rather than adding a new Resolution-Date header, I suggest we keep the existing Resolution header and change the text to the date.

For example, from:

> **Resolution:** [Discourse message](https://discuss.python.org/t/39233/312)

To:

> **Resolution:** [10-Oct-2024](https://discuss.python.org/t/39233/312)
