### ISSUE TITLE
PEP 496: Possible typo

### ISSUE THREAD

**Issue by zmeir** [python/peps#4076]
This issue refers to this specific line:  
https://github.com/python/peps/blob/main/peps/pep-0496.rst?plain=1#L129
![image](https://github.com/user-attachments/assets/7ce6caad-fa71-4bea-82fb-6585cd9aab03)

This seems to give the wrong version number for python>=3.10.  
For example:
![image](https://github.com/user-attachments/assets/6c6171b0-46aa-43ae-88f2-fcfeb7d79952)

**Comment by AA-Turner** [comment]
This is a rejected PEP from many years before Python 3.10. See also e.g. [flake8-2020](https://github.com/asottile-archive/flake8-2020).

A
