### ISSUE TITLE
PEP 691: Wrongly reference to PEP 529

### ISSUE THREAD

**Issue by ProFatXuanAll** [python/peps#4088]
I believe that all the references to [PEP-529](https://peps.python.org/pep-0529/) in [PEP-691](https://peps.python.org/pep-0691/) should be [PEP-592](https://peps.python.org/pep-0592/).

Referring issue: https://github.com/pypa/packaging.python.org/issues/1622

**Comment by hugovk** [comment]
PEP 691 is JSON-based Simple API for Python Package Indexes). 

PEP 592 (Adding “Yank” Support to the Simple API) would indeed make more sense than PEP 529 (Change Windows filesystem encoding to UTF-8).

Would you like to open a PR?
