### ISSUE TITLE
Why the PEP201 is empty?

### ISSUE THREAD

**Issue by imahobbit** [python/peps#442]
Someone wirte down a head and a tail. but where is the body？？？

**Comment by warsaw** [comment]
PEP 201 looks fine to me both online and in the repo.  What do you mean?

**Comment by imahobbit** [comment]
@warsaw 
I'm sorry I typing the wrong number, Is PEP210. Not PEP201. 

> PEP: 210
Title: Decoupling the Interpreter Loop
Version: $Revision$
Last-Modified: $Date$
Author: davida@activestate.com (David Ascher)
Status: Rejected
Type: Standards Track
Content-Type: text/x-rst
Created: 15-Jul-2000
Python-Version: 2.1
Post-History:
            # where is the body？？？
..
  Local Variables:
  mode: indented-text
  indent-tabs-mode: nil
  End:

**Comment by warsaw** [comment]
This was probably back in the day when we added placeholder PEPs.  These aren't the PEPs you're looking for.

**Comment by imahobbit** [comment]
Can you add a placeholder symbols for the placeholder PEPs?
    Thank you very much.

**Comment by warsaw** [comment]
What is "a placeholder symbol"?  Can you describe what actual problem you observe?

**Comment by brettcannon** [comment]
Probably a note saying "this space intentionally left blank" or something would probably suffice.

**Comment by warsaw** [comment]
Is this to insider-y? 

> This PEP is no more! It has ceased to be! It's expired and gone to meet its maker! It's a stiff! Bereft of life, it rests in peace! If you hadn't nailed it to the perch it'd be pushing up the daisies! It's metabolic processes are now 'istory! It's off the twig! It's kicked the bucket, It's shuffled off its mortal coil, run down the curtain and joined the bleedin' choir invisible!! THIS IS AN EX-PEP!!

**Comment by pfmoore** [comment]
Nah, mate. It's just pinin' for the fjords.
