### ISSUE TITLE
Sample implementation url(http://python.org/sf/1681101) in PEP 3115 is invalid

### ISSUE THREAD

**Issue by dragonly** [python/peps#446]
http://python.org/sf/1681101 will redirect to http://legacy.python.org/sf/1681101, which is 403 Forbidden.

**Comment by brettcannon** [comment]
I'm closing this issue as I don't quite see how this involves the PEP development process. If you're saying there is a dead link in a PEP, then please let us know which PEP or submit a PR to update it (you're probably looking for https://bugs.python.org/issue1681101).

**Comment by ethanhs** [comment]
@brettcannon it is a dead link in a PEP. The OP mentions PEP 3115 in the issue title and indeed the mentioned link is here https://github.com/python/peps/blob/master/pep-3115.txt#L250. I'll make a PR.

**Comment by brettcannon** [comment]
Sorry for the mix-up, @dragonly and thanks for the PR @ethanhs !
