### ISSUE TITLE
PEP 257: "XXX Mention docstrings of 2.2 properties." looks like an incomplete to-do

### ISSUE THREAD

**Issue by jamesray1** [python/peps#484]
https://www.python.org/dev/peps/pep-0257/

**Comment by brettcannon** [comment]
Yep, although I'm not sure what @goodger or @gvanrossum intended for that comment. I'm guessing guidance for properties themselves?

**Comment by gvanrossum** [comment]
I don't recall exactly. Maybe it refers to how docstring extraction tools may handle docstrings for properties? The issues there could be

- Presumably properties are documented as attributes, not as methods
- Getter and setter may both have docstrings; how to merge these
- There's an alternate notation where you can write
   ```
   attr = property(getter, setter, doc="some docstring")
   ```
- properties have a `__doc__` attribute

I'm not sure how I would update the PEP though -- I would actually probably just delete this (alternatively, you could research what pydoc does for properties and legitimize that).
