### ISSUE TITLE
Typo in directory name

### ISSUE THREAD

**Issue by tomasbedrich** [python/peps#533]
`dist.info` vs `dist-info`?

https://github.com/python/peps/blob/782c072ba994396972978a406f46dba6d1d09ebd/pep-0427.txt#L83

**Comment by brettcannon** [comment]
@ncoghlan Is this a typo?

**Comment by ncoghlan** [comment]
It is - the correct name is listed in subsection (a) for both "Unpack" and "Spread". @tomasbedrich's PR makes this reference consistent with those.

Thanks for the report Tomas!
