### ISSUE TITLE
PEP227 Placeholders

### ISSUE THREAD

**Issue by csabella** [python/peps#557]
On the bug tracker, [issue 11023](https://bugs.python.org/issue11023) was opened to report the presence of many `XXX` placeholders in PEP227.  R. David Murray reopened it with the statement that [there wasn't any other place to track PEP bugs](https://bugs.python.org/issue11023#msg127640).  Now that there is another place, moving the issue here.

If it's not relevant, feel free to close this.

**Comment by brettcannon** [comment]
At this point we should probably just delete the `XXX` comments.
