### ISSUE TITLE
PEP 8 - Allow single-line if with continue or break statements

### ISSUE THREAD

**Issue by Soaku** [python/peps#598]
The title describes a lot here.

It's a very common practice in a lot of languages to include if statements in a loop that "filter" the result.

``` python
for msg in msgs:
    # This message has already been parsed
    if msg.id <= last: continue

    # This message is owned by the bot
    if is_bot(msg.author["nick"]): continue
```

Here, PyCharm tells me that the code is not PEP-8 compliant because of the single-line statements.

I'd suggest to allow such use of single-line if's. They aren't here to ban them entirely. If an `if` is followed by a `continue`, `break`, `pass` or any other built-in word statement, it shouldn't break the styling rule. 

PEP-8 is defined as `Style Guide for Python Code`, here such usage of single-line `if's` looks definitely better than multi-line.

**Comment by warsaw** [comment]
Sorry, gotta disagree with you about single lines looking better than multilines.  Of course PEP 8 is a recommendation, so if your tool (i.e. PyCharm) complains about your preferred style, you'll have to configure the tool.  But I'm -1 on changing the PEP here.
