### ISSUE TITLE
update pep 282 log.warn -> log.warning ?

### ISSUE THREAD

**Issue by Carreau** [python/peps#638]
pep 282 refers to `log.warn`, which has been [deprecated](https://docs.python.org/3/library/logging.html#logging.Logger.warning) in favor of `log.warning`  since ... well a while but documentation does not say. 

Should the pep be updated accordingly ?

In particular, `Lib/distutils/log.py` in CPython source says:

```
# The class here is styled after PEP 282 so that it could later be
# replaced with a standard Python logging implementation.
```

But does not implement `warning`, just `warn`, and can't both follow the pep and be replaced by Python logging at the same time if they are inconsistant.

**Comment by warsaw** [comment]
PEPs are not documentation.  They are the historical record of the discussion.  In general, Standards Track PEPs should not be updated, but Informational PEPs can be.
