### ISSUE TITLE
Can I use issue here instead of python-ideas mailing list?

### ISSUE THREAD

**Issue by arekbulski** [python/peps#65]
I would like to propose a new PEP and have a discussion here. Is that okay? Mailing list is soo uncomfortable.

**Comment by warsaw** [comment]
I'm sorry that the mailing lists can sometimes be painful to interact with.  Maybe you can reach out to the PEP editors <peps@python.org> or other well-known, helpful developers, or folks who have been successful getting PEPs accepted, to help you.  It is admittedly a fairly high bar to get new features into Python these days.

I'm of mixed thoughts on using the GitHub tracker for new PEPs.  First, it's just about as public as any other forum, so I think you can expect the same high level of rigor here as anywhere else.  Also, at some point, posting PEPs to mailing lists (e.g. python-dev) is a *required* part of the process, because that's the place that most Python developers who are evolving the language keep track of.

So I'd say: if python-ideas is too daunting at first, send an email to peps@python.org to see if your idea should go to the next level.

**Comment by Rosuav** [comment]
The creation of a PEP is only one of many possible results from a python-ideas discussion. An idea can get proposed that gets such universal acceptance that it goes straight to the issue tracker with a patch. Or maybe the idea has already been implemented, and the solution is to update the documentation to make it more visible. PEPs tend to be for the most controversial ideas, where you need to set down the full pros and cons, and/or discuss multiple possible implementations or sub-ideas.

In addition to Barry's suggestion: You can take your idea to the main Python discussion list python-list@python.org (or the comp.lang.python newsgroup) too. There are plenty of people there who'll be happy to discuss your thoughts, and if you get support there, you can go to python-ideas with some allies.

**Comment by arekbulski** [comment]
I created an issue for my proposal. #66

**Comment by ned-deily** [comment]
@arekbulski As others have noted, please do NOT start discussions of new PEPs on the github issue tracker.   That's not how our process works.  The main problem is that such discussions will not be seen by the proper audience.

**Comment by arekbulski** [comment]
None of them said I should not post it here, Ned.

**Comment by ned-deily** [comment]
Sorry, that's how I read @warsaw and @Rosuav 's comments.  And, in any case, that's how things work for us.  We're going through a big transition right now with moving source code to github and there are many things in transition.  We need to be careful about making too many changes at once.  At some point in the future, it *may* make sense to change the PEP process but, IMO, this is not the time to do so and certainly not without discussion in the proper forums.

**Comment by arekbulski** [comment]
Ned, sorry but how you read it does not change what they said. You closed the issue on your own authority only and pushing that onto those two is dishonest.

I am not suggesting that we dismantle mailing lists. I just want to have some space for debate.

**Comment by ned-deily** [comment]
@arekbulski, You're not helping your case here.  I'm not trying to deflect responsibility.  We already have a space for debate, our mailing lists.  Please use them.

**Comment by Rosuav** [comment]
FWIW, I agree with Ned. Please use the mailing list; the people who follow the PEP repository are the handful of PEP editors, not the larger number of people who follow python-ideas.

**Comment by warsaw** [comment]
@arekbulski All I was trying to do was to help you ease into the process by suggesting ways to get some more friendly feedback on your idea.  Ultimately, it must go through the process.  I support @ned-deily and others responses.

**Comment by holdenweb** [comment]
+1. There is a process, and Dev team members are expected to comply. Not everyone with interest in an issue even follows the bug tracker.

**Comment by arekbulski** [comment]
Thank you for clarifying. I will learn how to use the mailing list.

**Comment by arekbulski** [comment]
For those not following the python-ideas mailing list: 

I proposed moving onto GitHub and a kind of consensus was made that I should create my own repo as a forum, which I did. I posted my initial proposal there and everyone are welcome to post there new topics.
https://github.com/arekbulski/python-ideas/issues

**Comment by holdenweb** [comment]
Would an instance of Atlassians Confluence be helpful? S

**Comment by dagnelies** [comment]
+1 on using github to send PEPs and pull requests. It's much easier and practical.

Mailing lists did their job, but it's time to move on. I think that by staying outside github's workflow, you're missing a *lot* of contributions and discussions.
