### ISSUE TITLE
Make PEP 12 more template-y

### ISSUE THREAD

**Issue by encukou** [python/peps#655]
PEP 12 (Sample reStructuredText PEP Template) seems more of a set of instructions or a tutorial, instead of a template. Instead, it should be something that you can actually grab and use.

Discussion on this started in #485 ("PEPs should include a section on "teachability"):

@Rosuav
> [A “teachability” section sounds] like something worth including in PEP 12. I'm -0.5 on requiring it in every PEP, but +1 on having a nice template that hints at important sections. In fact, I'd go a bit further and have other useful sections in PEP 12, eg "Backward compatibility" (or "Impact on existing code") and "Sample implementation", with bodies explaining the purposes of those sections. PEP authors can remove those sections if they don't apply, or keep them and flesh them out.

@njsmith
> Right now PEP 12 is mostly a ReST tutorial. It does seem like something more PEP-specific might be a better use of that space.

@Mariatta 
> For now PEP 12 seems more of a set of instructions or a tutorial, instead of a template, for me anyways. When I think of a template, I think of a cookiecutter-like template :)

@Rosuav 
> I agree, Mariatta, a template should be something that you can actually grab and use. PEP 12 has instructions at the top that act like that, but then the rest of the content isn't all template-y. So my view is that we should push for PEP 12 to be more template-y :)

@warsaw 
> +1 - that’s certainly the intent implied by the title of the PEP <wink>

**Comment by AA-Turner** [comment]
#2181 updated PEP 12 to include a template PEP, so I think this has been resolved.

A
