### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by 6502** [python/peps#658]
It's "dilemma" not "dilemna"

**Comment by pradyunsg** [comment]
@6502 where? Could you provide the url where you found this typo?

**Comment by 6502** [comment]
Sorry... i didn't realize this was for all peps. It's in pep-0576.rst.

**Comment by pradyunsg** [comment]
No issues. :)

Indeed, the typo is on line 23, first sentence of the Motivation section.

**Comment by brettcannon** [comment]
Fixed!
