### ISSUE TITLE
Please always mention the PEP number in PR/commit subject lines

### ISSUE THREAD

**Issue by gvanrossum** [python/peps#706]
I'd like to introduce a convention that PRs (and direct commits) for this repo should always have the PEP number in their subject line, with the exception of changes that affect the infrastructure (e.g. pep2html.py). I'd recommend the format "PEP NNN: <description of change>" but it's also okay to use e.g. "Fix typos in PEP NNN".

What's a good place to put such a convention?

**Comment by Mariatta** [comment]
It can be added to a .github/contributing.md file that will become a [contributing guideline](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) for the peps repo.
