### ISSUE TITLE
Does github support of commit squashing meet repo history requirements?

### ISSUE THREAD

**Issue by fgregg** [python/peps#71]
I'm not sure if this repo is the right place to discuss proposed peps, so please let me know if there's a better forum.

In PEP 0512, under the [Document steps to commit a pull request](https://github.com/python/peps/blob/master/pep-0512.txt#L268) section, there is a preference described for one commit for each single change. I'm not exactly clear what this means, but I think this might mean that each merged PR should show up as a single commit, no matter how many commits the developer made while developing the PR.

If that is so, would github's facility to squash commits for PR's meet this requirement? https://help.github.com/articles/about-pull-request-merge-squashing/

Attn @brettcannon

**Comment by brettcannon** [comment]
This issue tracker is for managing PEPs, not the individual PEPs themselves, so it's unfortunately not the right place.

For PEP 512, (a) that discussed  on the [core-workflow](https://mail.python.org/mailman/listinfo/core-workflow) mailing list, and (b) as the author of the PEP and can tell you that yes, GitHub's commit squashing does what we want. 😄
