### ISSUE TITLE
Prohibit unparenthesized assignment expressions used combined with keyword argument

### ISSUE THREAD

**Issue by zhangyangyu** [python/peps#721]
This example `foo(x := 3, cat='vector')` is valid right now in PEP572. But I think this is rather confusing, wrongly take it as another form of keyword argument assignment. Is it possible to require parenthesized assignment expressions here? Unparenthesized form can still be used if there are only positional arguments.

**Comment by gvanrossum** [comment]
Sorry, this would be too complex for the parser, since we definitely want to allow unparenthesized assignment expressions in positional arguments. Argument list syntax is already hellishly complex. We'll have to rely on common sense.
