### ISSUE TITLE
Reserve a PEP number for "Recommendations for Type Stubs"

### ISSUE THREAD

**Issue by srittau** [python/peps#743]
Upcoming Informational PEP per https://mail.python.org/pipermail/python-dev/2018-July/154676.html. Title is subject to change. Author list looks to be:

* Jelle Zijlstra &lt;jelle.zijlstra@gmail.com>
* Rebecca Chen &lt;rechen@google.com>
* Teddy Sudol &lt;tsudol@google.com>
* Sebastian Rittau &lt;srittau@rittau.biz>

Thanks!

**Comment by Mariatta** [comment]
You don't have to reserve a number.
New PEPs are to be numbered 9999. Once you have the draft and made the pull request, we'll assign a number to you.
See the [contributing guidelines](https://github.com/python/peps/blob/master/CONTRIBUTING.rst) and PEP-1 of the workflow.
