### ISSUE TITLE
PEP 566: make Supported-Platform optional?

### ISSUE THREAD

**Issue by armijnhemel** [python/peps#792]
it would be very helpful to clarify the status of "Supported-Platform" in PEP 566. Right now it reads (from PEP 345):

    Binary distributions containing a PKG-INFO file will use the Supported-Platform field in their metadata
    to specify the OS and CPU for which the binary distribution was compiled.

but when looking at the PKG-INFO files I can find on my system I see that none of them (excluding the 1.0 files, where it was not defined) have the "Supported-Platform" tag. Instead people seem to be using the "Platform" tag for it. It makes me wonder if the "Supported-Platform" tag is actually that useful.

**Comment by brettcannon** [comment]
@armijnhemel this is best brought up on the distutils-sig mailing list.
