### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by brettcannon** [python/peps#8]
I'm talking to our lawyer to find out what the best license is.

**Comment by birkenfeld** [comment]
All PEPs are required to say "This document has been placed in the public domain.", which AIUI is of questionable value in some jurisdictions.

But it would suggest a maximally permissive license to keep the spirit of things.

**Comment by turicas** [comment]
You may adopt a Creative Commons license (like [CC0](https://creativecommons.org/publicdomain/zero/1.0/)) since the "public domain" is different in many countries (in Brazil, for example, "public domain" requires citation).

**Comment by brettcannon** [comment]
I talked with @VanL and he said we don't need a license since every PEP is explicitly placed in the public domain.
