### ISSUE TITLE
Python: Add 'params' to 'function' tooltips.

### ISSUE THREAD

**Issue by C-PyLx** [python/peps#823]
We wants from you to add (function parameters) into (functions) tooltip.

This property helps us to find the parameters in our pro programs.
![issue_li](https://user-images.githubusercontent.com/40021473/47746259-082cde80-dc9b-11e8-9a94-2106f9324342.jpg)

**Comment by Rosuav** [comment]
This repository is an administrative one for the management of Python Enhancement Proposal documents. What you're looking for is a Visual Studio Code feature, so I recommend raising it with VSCode.
