### ISSUE TITLE
Pep 440 question/clarification Version specifiers no "Or" available.

### ISSUE THREAD

**Issue by Carreau** [python/peps#85]
I was reading pep 440 and in particular the "Version specifier section".

The following sentence caught my eye:

> The comma (",") is equivalent to a logical and operator: a candidate version must match all given version clauses in order to match the specifier as a whole.

Is there no way to have a "or" ? It seem to me that it might be useful for package that want to express compatibility with `2.6`, `2.7` or `>3.3` for example, in the form `=~2.6 <or operator> =~3.3`.

I completely agree that the use case is _limited_ and rare, I was just wondering if I'm missing something, if it was an oversight and if not if adding a section detailing that "or" was not considered, or that "or" was explicitly not included for X,Y,Z reason would be a good thing. 

Thanks,

**Comment by brettcannon** [comment]
We're trying to keep the peps repo's issue tracker about the PEP process and managing PEPs, not the PEPs themselves. This question is best asked on distutils-sig where @ncoghlan or someone can answer it.
