### ISSUE TITLE
Broken link on the PEP-3104 page

### ISSUE THREAD

**Issue by jraman** [python/peps#897]
**Description**
The following reference link on the [PEP 3104](https://www.python.org/dev/peps/pep-3104/) page is broken:
 http://www.python.org/search/hypermail/python-1994q1/0301.html

**To Reproduce**
1. Go to https://www.python.org/dev/peps/pep-3104/
2. Click on the link in the first reference.  The link is: http://www.python.org/search/hypermail/python-1994q1/0301.html
3. The following error is seen: Error 404: File not Found

**Expected behavior**
Expected to go to a page such as [this one](ftp://ftp.ntua.gr/mirror/python/search/hypermail/python-1994q1/0301.html) and not see the 404 error.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Browser: Chrome
 - Version: 71.0.3578.98

[Copied from https://github.com/python/pythondotorg/issues/1388.  Reposting here per their request.]

**Comment by willingc** [comment]
Thanks @jraman for the report. The link should actually point to the legacy website of python.org: https://legacy.python.org/search/hypermail/python-1994q1/0301.html

@warsaw What do you think is the best way to handle PEP links that should redirect to the legacy site but no longer do so?
