### ISSUE TITLE
spelling error in PEP219 introduction

### ISSUE THREAD

**Issue by nanjekyejoannah** [python/peps#899]
Am moving an issue from the bug tracker here. This was reported by 景云鹏 here : https://bugs.python.org/issue36090

In the introduction for PEP 219. In the second paragraph here : https://www.python.org/dev/peps/pep-0219/#introduction

It is written "in more that a year" instead of "in more that a year"

**Comment by Harmon758** [comment]
> It is written "in more that a year" instead of "in more that a year"

It is written "in more that a year" instead of "in more **than** a year"
