### ISSUE TITLE
Set up IRC hook for #python-dev

### ISSUE THREAD

**Issue by berkerpeksag** [python/peps#9]
We need to replace irker with GitHub's IRC hook.

**Comment by dstufft** [comment]
We'll need to decide between a spurious join/part for every push, or dropping the ``+n`` from the #python-dev channel modes so that the IRC bot can send a message to the channel without joining it.

**Comment by zware** [comment]
#python-dev is already -n for the devguide repo, so the IRC service just needs to be turned on here.

**Comment by berkerpeksag** [comment]
I just enabled the IRC service on python/peps.
